name: Deploy github pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: bobmk2/my-react-components@master

    - name: Build
      run: yarn gh-pages:build

    - name: Deploy
      run: yarn gh-pages:deploy
