name: Deploy github pages

on:
  push:
    branches: [master]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Setup
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: gh-pages:build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./storybook-static
